export const LOADING = "LOADING";
export const ERROR = "ERROR";

export const SEARCH_COMPANY = "SEARCH_COMPANY";
export const RESET_SEARCH_RESULTS = "RESET_SEARCH_RESULTS";
export const SET_SEARCHED_COMPANY = "SET_SEARCHED_COMPANY";

export const GET_OVERVIEW_DATA = "GET_OVERVIEW_DATA";
export const GET_FINANCIAL_DATA = "GET_FINANCIAL_DATA";